create table USUARIO (
        ID NUMBER(4, 0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        USERNAME VARCHAR(20) NOT NULL,
        PWD_HASH VARCHAR(20) NOT NULL,
        SALT VARCHAR(5) NOT NULL,
        EMAIL VARCHAR(40 BYTE) NOT NULL
);

CREATE TABLE PALABRA (
    ID NUMBER(5, 0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PALABRA VARCHAR(18) NOT NULL
);


create TABLE PROGRESO (
    ID_USER NUMBER(4, 0),
    ID_PALABRA NUMBER(5, 0),
    INTENTOS NUMBER(1, 0)
);

ALTER TABLE PROGRESO ADD FOREIGN KEY (ID_USER) REFERENCES USUARIO(ID);
ALTER TABLE PROGRESO ADD FOREIGN KEY (ID_PALABRA) REFERENCES PALABRA(ID);